* Matlab & Octave Utilities

Simple utilities and helper M-files I keep on my Maltab & Octave PATHs.  All of the codes work in both Matlab & Octave.

  - =hist2d.m= ::
     Compute a bivariate histogram over a rectilinear grid. 
  - =plotFreqSpec.m= ::
     Plot samples & FFT of samples with linear & logarithmic scales
  - =plotCurveFile.m= ::
     Read a columnar numeric file from disk, and plot an Y curve, X-Y parametric curve, or X-Y-Z surface.
  - [[https://github.com/richmit/MatlabUtils/blob/main/runningOn.m][~runningOn.m~]] ::
     Return true if the code is running on the given platform (MATLAB, SciLab, Octave).
  - =simplifyCurveEuc.m= ::
    Reduce a set of points so that adjacent points are not too close together in space.
  - =sumByBlocks.m= ::
    Bust an array of samples into fixed size blocks, compute stats for each block, and return it all in a matrix. The
    columns of the matrix are mean, min, and max.
  - =applyToRows.m= & =applyToCols.m= ::
    Apply a function to the rows or columns of a matrix.  Reminiscent of, but far less elegant than, the R =apply= functions.

I use the script =install.sh= to copy these files into my Matlab & Octave paths.

-mitch

PS: Have Fun
